// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8SJB9mu1yA6pIi_6eEh86GO15rUIZDw',
    appId: '1:427993512959:web:18b458e9fa64f96ac085ca',
    messagingSenderId: '427993512959',
    projectId: 'eventplaning-withamira-app',
    authDomain: 'eventplaning-withamira-app.firebaseapp.com',
    storageBucket: 'eventplaning-withamira-app.firebasestorage.app',
    measurementId: 'G-V0GMR56ZZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw775hN_wuuHNM0j3tVZdxPcDToNYhp-g',
    appId: '1:427993512959:android:4c1d54440fa6b38ac085ca',
    messagingSenderId: '427993512959',
    projectId: 'eventplaning-withamira-app',
    storageBucket: 'eventplaning-withamira-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFFPC9rGsV_TghOA0vKXrSGqDJiVVfPKU',
    appId: '1:427993512959:ios:7cf86c3ce9e0547bc085ca',
    messagingSenderId: '427993512959',
    projectId: 'eventplaning-withamira-app',
    storageBucket: 'eventplaning-withamira-app.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFFPC9rGsV_TghOA0vKXrSGqDJiVVfPKU',
    appId: '1:427993512959:ios:7cf86c3ce9e0547bc085ca',
    messagingSenderId: '427993512959',
    projectId: 'eventplaning-withamira-app',
    storageBucket: 'eventplaning-withamira-app.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh8SJB9mu1yA6pIi_6eEh86GO15rUIZDw',
    appId: '1:427993512959:web:63c4d7714f89629fc085ca',
    messagingSenderId: '427993512959',
    projectId: 'eventplaning-withamira-app',
    authDomain: 'eventplaning-withamira-app.firebaseapp.com',
    storageBucket: 'eventplaning-withamira-app.firebasestorage.app',
    measurementId: 'G-RR7S2B60PR',
  );
}
